-- Supabase/PostgreSQL schema for the Bibliotheque CPS project.
-- Execute this file first in the Supabase SQL editor.

create extension if not exists pgcrypto;

do $$
begin
    create type user_role as enum ('admin', 'bibliothecaire', 'assistant');
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type user_statut as enum ('actif', 'inactif');
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type membre_type as enum ('eleve', 'enseignant');
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type emprunt_statut as enum ('en_cours', 'retourne', 'en_retard');
exception
    when duplicate_object then null;
end $$;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    nom varchar(100) not null,
    email varchar(100) not null unique,
    password varchar(255) not null,
    role user_role not null default 'bibliothecaire',
    statut user_statut not null default 'actif',
    created_at timestamptz not null default now()
);

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    nom varchar(100) not null,
    description text,
    created_at timestamptz not null default now()
);

create table if not exists public.livres (
    id bigint generated by default as identity primary key,
    titre varchar(200) not null,
    auteur varchar(150) not null,
    isbn varchar(50) not null unique,
    numero_etagere varchar(50) not null,
    date_edition date,
    quantite_totale integer not null default 1,
    quantite_disponible integer not null default 1,
    created_at timestamptz not null default now(),
    constraint livres_quantite_totale_positive check (quantite_totale >= 0),
    constraint livres_quantite_disponible_valid check (
        quantite_disponible >= 0
        and quantite_disponible <= quantite_totale
    )
);

create table if not exists public.livre_categorie (
    livre_id bigint not null references public.livres(id) on delete cascade,
    categorie_id bigint not null references public.categories(id) on delete cascade,
    primary key (livre_id, categorie_id)
);

create table if not exists public.membres (
    id bigint generated by default as identity primary key,
    nom varchar(100) not null,
    prenom varchar(100),
    classe varchar(50) not null,
    type membre_type not null default 'eleve',
    telephone varchar(20),
    email varchar(100),
    created_at timestamptz not null default now()
);

create table if not exists public.emprunts (
    id bigint generated by default as identity primary key,
    membre_id bigint not null references public.membres(id) on delete restrict,
    livre_id bigint not null references public.livres(id) on delete restrict,
    date_emprunt date not null,
    date_retour_prevue date not null,
    date_retour_reelle date,
    statut emprunt_statut not null default 'en_cours',
    amende_montant numeric(10, 2) not null default 0,
    amende_payee boolean not null default false,
    created_at timestamptz not null default now(),
    constraint emprunts_amende_positive check (amende_montant >= 0),
    constraint emprunts_retour_reelle_when_retourne check (
        statut <> 'retourne'
        or date_retour_reelle is not null
    )
);

create table if not exists public.parametres (
    id bigint generated by default as identity primary key,
    duree_emprunt_jours integer not null default 15,
    max_livres_par_membre integer not null default 3,
    amende_par_jour numeric(10, 2) not null default 5000,
    created_at timestamptz not null default now(),
    constraint parametres_duree_positive check (duree_emprunt_jours > 0),
    constraint parametres_max_livres_positive check (max_livres_par_membre > 0),
    constraint parametres_amende_positive check (amende_par_jour >= 0)
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    message text not null,
    type varchar(50) not null default 'retard',
    vue boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_livres_titre on public.livres (titre);
create index if not exists idx_livres_auteur on public.livres (auteur);
create index if not exists idx_livres_numero_etagere on public.livres (numero_etagere);
create index if not exists idx_membres_nom on public.membres (nom);
create index if not exists idx_membres_classe on public.membres (classe);
create index if not exists idx_emprunts_membre_id on public.emprunts (membre_id);
create index if not exists idx_emprunts_livre_id on public.emprunts (livre_id);
create index if not exists idx_emprunts_statut on public.emprunts (statut);
create index if not exists idx_emprunts_date_retour_prevue on public.emprunts (date_retour_prevue);
create index if not exists idx_notifications_vue on public.notifications (vue);

