-- Create or reset an application admin account.
-- Execute this file in Supabase SQL editor after 01_schema.sql.
--
-- Login:
--   email: admin@cps.com
--   password: admin123
--
-- The password hash is generated by pgcrypto and remains compatible with
-- PHP password_verify().

create extension if not exists pgcrypto;

insert into public.users (nom, email, password, role, statut)
values (
    'Administrateur',
    'admin@cps.com',
    crypt('admin123', gen_salt('bf', 10)),
    'admin',
    'actif'
)
on conflict (email) do update set
    nom = excluded.nom,
    password = excluded.password,
    role = excluded.role,
    statut = excluded.statut;

